name: Build index.html every 30 minutes

on:
  schedule:
    - cron: "*/30 * * * *"   # runs every 30 minutes (UTC)
  workflow_dispatch:         # allow manual run

permissions:
  contents: write            # allow committing back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Run generator
        shell: bash
        run: |
          chmod +x ./run.command || true
          ./run.command || python generate_index.py

      - name: Commit index.html if changed
        run: |
          if git status --porcelain | grep -q "index.html"; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add index.html
            git commit -m "Auto-build index.html [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
