name: Build & Deploy to Cloudflare Pages (every 30 min)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write        # <-- allows committing back to the repo
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Run generator
        shell: bash
        run: |
          chmod +x ./run.command || true
          ./run.command || python generate_index.py

      - name: Prepare site folder (index + config + headers)
        run: |
          rm -rf _site
          mkdir -p _site
          cp -a index.html _site/
          [ -f config.json ] && cp -a config.json _site/ || true
          [ -f _headers ] && cp -a _headers _site/ || true

      # >>> Commit generated index.html back to GitHub <<<
      - name: Commit generated files
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A index.html config.json _headers || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update generated index.html [skip ci]"
            git push
          fi

      - name: Publish to Cloudflare Pages (Production)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: 1i6MFwiicbFakRcKlUq0KF3ho88FMTDMuNGF-WZE
          accountId: c7b2bb3a435b4434235f331853e0bb5e
          projectName: allenslists
          directory: _site
          branch: main
          gitHubToken: ${{ secrets.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 }}
          wranglerVersion: "4"
