name: Build & Deploy to Cloudflare Pages (every 30 min)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  deployments: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install generator deps
        run: |
          python -m pip install --upgrade pip
              pip install pandas openpyxl
          # if your generator needs pandas/requests/etc, install here
          # pip install -r requirements.txt || true

      - name: Run generator (build index + CSV)
        run: |
          python generate_index.py
          echo "::notice title=Generator::Ran generate_index.py"

      - name: Prepare _site (copy artifacts)
        run: |
          rm -rf _site
          mkdir -p _site/data
          # index.html is created at repo root; copy it
          cp -a index.html _site/
          # copy headers (CORS)
          if [ -f "_headers" ]; then cp -a _headers _site/; fi
          # copy JSON config if you have one
          if [ -f "config.json" ]; then cp -a config.json _site/; fi
          # copy the CSV generated by the script
          if [ -f "data/prices.csv" ]; then cp -a data/prices.csv _site/data/prices.csv; fi

      - name: Publish to Cloudflare Pages (Production)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: 1i6MFwiicbFakRcKlUq0KF3ho88FMTDMuNGF-WZE
          accountId: c7b2bb3a435b4434235f331853e0bb5e
          projectName: allenslists
          directory: _site
          branch: main
          gitHubToken: ${{ secrets.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 }}
          wranglerVersion: "4"


